# Generated by Django 6.0.3 on 2026-03-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
