# Generated by Django 6.0.3 on 2026-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0002_remove_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
