# Generated by Django 6.0.3 on 2026-03-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
