# Generated by Django 6.0.3 on 2026-03-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0003_feedback_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
